#
# Script to test roxut package action on package roxutTestPkg
#
# This script roxygenizes, roxut's, build checks and installs
# roxutTestPkg as a means of ensuring that roxut functions
# as intended
#
# If this script is run by R CMD check (e.g. via make) then everything here is
# executed in ...roxut/roxut.Rcheck which is the check folder/environment.
# Messages go to ...roxut/roxut.Rcheck/tests/tinytest.Rout
#
# Step 1. Ensure that roxygenize and roxut work

message("\n\n>>> Beginning testing of roxutTestPkg")
test_dir <- getwd()
setwd("roxutTestPkg") # move to the dir for the next steps
message(">>> roxygenizing")
roxygenize()
message(">>> Running roxut")
roxut()

# Step 2. Verify that roxut updated the unit test files in roxutTestPkg
# When roxygenize() was run above the package roxutTestPkg was loaded.
# The loaded roxutTestPkg is in ...roxut/roxut.Rcheck/roxut/tinytest/roxutTestPkg
# which is the current working directory

tinytest_files <- list.files("inst/tinytest", "test_.*\\.R", full.names = TRUE)
for (i in 1:length(tinytest_files)) {
  tmp <- readLines(tinytest_files[i])[1]
  status <- grepl("roxut", tmp)
  if (!status) warning(paste("File", tinytest_files[i], "was not generated by roxut", sep = " "))
  if (status) message(paste("File", tinytest_files[i], "was generated by roxut", sep = " "))
}

testthat_files <- list.files("tests/testthat", "test_.*\\.R", full.names = TRUE)
for (i in 1:length(testthat_files)) {
  tmp <- readLines(testthat_files[i])[1]
  status <- grepl("roxut", tmp)
  if (!status) warning(paste("File", testthat_files[i], "was not generated by roxut", sep = " "))
  if (status) message(paste("File", testthat_files[i], "was generated by roxut", sep = " "))
}


# Step 3. Build and check package
# See WRE sec 1.6 for the need to call R this (safe) way
rhome <- Sys.getenv("R_HOME")
localR <- paste(rhome, "bin", "R", sep = "/")
system2(localR, c("-e 'library(roxygen2)'", "-e 'roxygenize()'"))

setwd(test_dir) # move up for the next actions
system2(localR, "CMD build roxutTestPkg")
system2(localR, "CMD check roxutTestPkg_0.1.tar.gz")
