#
# Script to test roxut package action on package roxutTestPkg
#
# This script roxygenizes using the tests_roclet, build checks and installs
# roxutTestPkg as a means of ensuring that roxut functions as intended
#
# If this script is run by R CMD check (e.g. via make) then everything here is
# executed in ...roxut/roxut.Rcheck which is the check folder/environment.
# Messages go to ...roxut/roxut.Rcheck/tests/tinytest.Rout
#

out <- tryCatch(
  {
    # Step 1. Run roxygenize with the tests_roclet

    message("\n\n>>> Beginning processing of roxutTestPkg")
    test_dir <- getwd()
    setwd("roxutTestPkg") # move to the dir for the next steps
    message(">>> roxygenizing using rd, namespace, collate & tests roclets")
    roxygenize(roclets = c("rd", "namespace", "collate", "tests_roclet"))

    # Step 2. Verify that roxut updated the unit test files in roxutTestPkg
    # When roxygenize() was run above the package roxutTestPkg was loaded.
    # The loaded roxutTestPkg is in ...roxut/roxut.Rcheck/roxut/tinytest/roxutTestPkg
    # which is the current working directory

    tinytest_files <- list.files("inst/tinytest", "test_.*\\.R", full.names = TRUE)
    for (i in 1:length(tinytest_files)) {
      tmp <- readLines(tinytest_files[i])[1]
      status <- grepl("roxut", tmp)
      if (!status) warning(paste("Warning: file", tinytest_files[i], "was not generated by roxut", sep = " "))
      if (status) message(paste("Confirming file", tinytest_files[i], "was generated by roxut", sep = " "))
    }

    testthat_files <- list.files("tests/testthat", "test_.*\\.R", full.names = TRUE)
    for (i in 1:length(testthat_files)) {
      tmp <- readLines(testthat_files[i])[1]
      status <- grepl("roxut", tmp)
      if (!status) warning(paste("Warning: file", tinytest_files[i], "was not generated by roxut", sep = " "))
      if (status) message(paste("Confirming file", tinytest_files[i], "was generated by roxut", sep = " "))
    }

    # Step 3. Build and check package
    # See WRE sec 1.6 for the need to call R this (safe) way
    rhome <- Sys.getenv("R_HOME")
    localR <- paste(rhome, "bin", "R", sep = "/")

    setwd(test_dir) # move up for the next actions
    message("\n\n>>> Building & checking roxutTestPkg")
    system2(localR, "CMD build roxutTestPkg")
    system2(localR, "CMD check roxutTestPkg_0.1.tar.gz")

    # Step 4. Check the output file for errors
    problem <- FALSE
    setwd("../..")
    setwd("tests")
    lines <- readLines("tinytest.Rout") # reading from an open file!
    if (any(grepl("There.*roxutTestPkg", lines))) problem <- TRUE
    if (!problem) message("tinytest.Rout is clean/no errors")
    if (problem) {
      message("tinytest.Rout has an error")
      stop("Encountered a problem while running test_roxutTestPkg.R")
    }
  },

  error = function(cond) {
    errmess <- "There was a problem processing & testing roxutTestPkg"
    message("\nError message from R: ", cond$message, "\n")
    message(errmess)
    return(NA)
  }
) # end of tryCatch
